[colors.primary]
foreground = "#d8d8d8"
background = "#000000"
dim_foreground = "#828482"
bright_foreground = "None"

[colors]
cursor = { text = "CellBackground", cursor = "CellForeground" }
vi_mode_cursor = { text = "CellBackground", cursor = "CellForeground" }

[colors.search]
matches = { foreground = "#181818", background = "#ac4242" }
focused_match = { foreground = "#181818", background = "#f4bf75" }

[colors.hints]
start = { foreground = "#181818", background = "#f4bf75" }
end = { foreground = "#181818", background = "#ac4242" }

[colors.normal]
black = "#1c1f24"
red = "#fc2025"
green = "#02f789"
yellow = "#f9fc5f"
blue = "#5ffcfc"
magenta = "#f067fc"
cyan = "#00b29e"
white = "#e9e2cb"

[colors.bright]
black = "#202020"
red = "#f4153b"
green = "#50ee84"
yellow = "#fcab20"
blue = "#20dbfc"
magenta = "#c61b6e"
cyan = "#00b27f"
white = "#fcf4dc"

[colors.dim]
black = "#101010"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F3B387"
blue = "#A0BEFE"
magenta = "#cba6cb"
cyan = "#90E2D5"
white = "#e9e2cb"
